// <auto-generated />
using CineBook.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CineBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710123000_AddSnacks")]
    partial class AddSnacks
    {
    }
}
