// <auto-generated />
using CineBook.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CineBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710120000_AddEmployees")]
    partial class AddEmployees
    {
    }
}
